src/helpers/__tests__/createMatchers.test.ts
src/helpers/__tests__/cssExtensions.test.ts
src/helpers/createMatchers.ts
src/helpers/cssExtensions.ts
src/index.ts

Resolve customMatcher issues

---

README.md
package.json
src/helpers/__tests__/__snapshots__/cssSnapshots.test.ts.snap
src/helpers/__tests__/classTransforms.test.ts
src/helpers/__tests__/createMatchers.test.ts
src/helpers/__tests__/fixtures/test.module.css
src/helpers/__tests__/fixtures/test.module.scss
src/helpers/createMatchers.ts
src/helpers/cssExtensions.ts
src/helpers/cssSnapshots.ts
src/index.ts
src/options.ts
yarn.lock

- A Less matcher is now included by default (#12).
- Improved support for Sass (#17).

Add extended Sass support

---

.prettierignore
package.json
src/helpers/__tests__/__snapshots__/cssSnapshots.test.ts.snap
src/helpers/__tests__/cssSnapshots.test.ts
src/helpers/__tests__/fixtures/test.module.less
src/helpers/cssSnapshots.ts
tsconfig.json
yarn.lock

This PR:
- Closes https://github.com/mrmckeb/typescript-plugin-css-modules/issues/19
- Closes https://github.com/mrmckeb/typescript-plugin-css-modules/issues/18

Add LESS support

---

src/index.ts

This PR tells TypeScript to search for the module using `baseUrl` and `paths`.
- Resolves #24.
- Resolves #25.

Resolve aliased imports

---

src/helpers/__tests__/fixtures/test.module.css
src/helpers/cssSnapshots.ts

Projects using PostCSS may have enabled plugins which can result in `.css` files that cannot be parsed by the Sass compiler. In my case, the [`postcss-mixins`](https://github.com/postcss/postcss-mixins) plugin uses a reserved Sass at-rule (`@mixin`) in an incompatible way, causing the transformer to fail.
Since PostCSS is able to extract nested selectors without any kind of transformation, we can pass in the source as-is for plain CSS files.

Leave .css files un-transformed

---

package.json
src/@types/postcss-import-sync2.d.ts
src/helpers/DtsSnapshotCreator.ts
src/helpers/__tests__/DtsSnapshotCreator.test.ts
src/helpers/__tests__/__snapshots__/DtsSnapshotCreator.test.ts.snap
src/helpers/__tests__/fixtures/import.module.css
src/helpers/__tests__/fixtures/import.module.less
yarn.lock

Fixes #47 and #48.
Adds support for local `@import` at-rules for pure css and less stylesheets.
It's done via passing proper `from`/`filename` to postcss/less renderers as discussed [here](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/48).
I've also added couple of tests and `postcss-import-sync2` dev dependency for those tests to work.
Unfortunatelly `*.scss` tests are failing for me with empty received snapshot (even at `origin/develop` without any modifications) and i've never worked with SCSS, so I did not dare to change anything related to scss. And I had to push with `--no-verify` to skip husky, but all other tests are passing.
As a side effect of those modifications local class names have changed: the common "file___" prefix is now substituted by real file name …

Add relative @import support

---

package.json
src/index.ts

Fixes #49 
Adds support for resolving `@import`s in `*.scss` files using the paths defined in `SASS_PATH` in a `.env` file at the project root.
Works by reading in the `.env` file during initialization and adding its `SASS_PATH` value (after some fix-up to relative paths) to `process.env.SASS_PATH`, where `dart-sass` will find it and use it.
Unfortunately, like #50 the other currently pending pull request on this repo, I too have failing `*.scss` tests with empty received snapshot, even with no modifications from upstream `origin/develop`.  All other tests are passing.

Add .env SASS_PATH support

---

src/helpers/DtsSnapshotCreator.ts
src/options.ts

This PR allows the user to pass options to the render function called for less or scss files.
My use-case for this is passing the `paths` option to the less configuration like this:
```json
{
"compilerOptions": {
"plugins": [
{
"name": "typescript-plugin-css-modules",
"options": {
"renderOptions": {
"less": {
"paths": ["src/"]
}
}
}
}
]
}
}
```
This allows me to use path aliases in my webpack config and match those in the less configuration to fix the import errors that occur because of said aliases.
In addition to that, I added some improvements to the error handling for when less fails to render the file. Previously, there would be an error like `Cannot read property 'css' of undefined` since the `output` is not passed into the callback if there was an error (I have made a PR to reflect …

Allow passing options to SCSS/Less render functions

---

src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/getClasses.ts

Previous code used explicit path slash to determine the folder path of a file, which only works if the OS in question uses that type of slash. Node's path library is OS-agnostic and avoids these issues.
Also of note, the `catch` here was using `console.log` instead of `logger.log`, which seemed wrong, but feel free to correct.
Fixes #62

Change getFilePath to use Node's path library

---

package.json
src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/fixtures/bootstrap.module.scss
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getClasses.ts
src/index.ts
yarn.lock

Resolves #66.
As it turns out, in TypeScript plugins, `process.cwd()` returns the root (`/`), and not the current working directory.
This sets that manually.

Fix Sass node module resolution

---

README.md
package.json
src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/fixtures/customTemplate.js
src/helpers/__tests__/fixtures/customTypescriptTransformer.js
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/createExports.ts
src/helpers/getClasses.ts
src/helpers/getDtsSnapshot.ts
src/index.ts
src/options.ts
yarn.lock

I am a new user of this plugin and I think it is awesome! 
Pardon my assumptions in posting a PR before we've discussed it. I wouldn't be offended if you rejected the idea, however, I think it is a nice feature that has merit and could prevent excess feature requests from this plugin in the future. 
The idea here is to provide a custom transformation function to allow users to transform the generated DTS before it is handed back to TSServer. This allows the dev to add additional info to the generated DTS, or generate a new set altogether. 
This is useful to me as I generate my own set of JS for runtime that does not quite match the standard CSS Module output that is generated from this plugin. 
Please let me know if you think this addition has merit and/or if there are changes you would …

Support a custom TS transformer for final DTS output

---

README.md
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getClasses.ts
src/helpers/getDtsSnapshot.ts
src/index.ts
src/options.ts

I fix the [issue#77](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/77),
I write a new npm package [`less-plugin-aliases`](https://www.npmjs.com/package/less-plugin-aliases) and inject `compilerOptions` into the `customRenderer` that I can resolve the `@import ~path` manually.
The general use case is as below:
```json5
{
"compilerOptions": {
"plugins": [
{
"name": "typescript-plugin-css-modules",
"options": {
"classnameTransform": "camelCase",
"customMatcher": "\\.less$",
"customRenderer": "node_modules/less-plugin-aliases/lib/customRender.js"
}
}
],
// ...
}
}
```
ps: My english is poor, maybe there are some mistakes in README.md, pls fix it if you find ~

feat: inject compilerOptions into customRenderer

---

src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/createExports.ts

Fixes #97
This avoids errors in the Webstorm IDE's TypeScript console.

Use let instead of const

---

package.json
src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/external/package/public.module.scss
src/helpers/__tests__/fixtures/tsconfig-paths.module.scss
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getClasses.ts
yarn.lock

Fixes #98 
Tried to find a way to use TypeScript to resolve the paths, but I could not. Did not want to implement the logic myself, hence a new dependency [tsconfig-paths](https://github.com/dividab/tsconfig-paths). Feedback welcome.

feat: sass support for tsconfig path aliases

---

package.json
src/@types/postcss-icss-keyframes.d.ts
src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/fixtures/test.module.css
src/helpers/__tests__/getDtsSnapshot.test.ts
src/index.ts
yarn.lock

Attempts to address #104 
I realised that postcss is doing the hard lifting, found an old library that seems to work.

Add keyframe support

---

README.md
src/helpers/getClasses.ts
src/options.ts

The current solution for dealing with sass/scss imports which are
prefixed with a tilde (~) is to strip the symbol from the import line.
This breaks down when dart-sass itself starts pulling in subsequent
imports that are also tilde-prefixed.
This change introduces a simple algorithm to climb the filesystem tree
looking for the imported module/file in a node_modules directory.
This is enabled by default since it replaces behavior which is already
forced on.
This change is covered under the existing "with a Bootstrap import"
test.

Improved Webpack-style tilde-import support for Sass

---

src/importers/__tests__/sassTildeImporter.ts
src/importers/sassTildeImporter.ts

Hello! 
Love this plugin so far, but ran into a couple issues trying to add it to my project. This might have only changed due to the  sass importer that was added with v3, but I wasn't able to import sass partials or css files. This PR adds support for those, as well as some test coverage for the sass importer.
The issue with sass partials being that sass will allow you import a partial, without including an underscore in the name. The sass importer as is would not resolve those files.
```scss
// can resolve './_colors.scss'
@import 'colors'
```
Sass also supports the importing of css files, so I included that case in the sass importer.

Support sass partials imports and css imports in sass files

---

package.json
src/importers/__tests__/sassTildeImporter.ts
src/importers/sassTildeImporter.ts
yarn.lock

This PR adds support for [index files](https://sass-lang.com/documentation/at-rules/use#index-files) in Sass.
With these changes the plugin supports writing `~library/folder` to import the `~library/folder/_index.scss` file.
The 'sass-svg' library is added for testing, this is the first publicly available library I found with an `_index.scss` file.

Support sass index files

---

README.md
src/index.ts
src/options.ts

Based on feedback and research, we'll deprecate `postCss[...]` in favour of `postcss[...]`. See #127 for notes.
Both will be supported for the foreseeable future - this should be a soft deprecation only.
Closes #127.

Move to lowercase `postcss`

---

README.md
src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/classTransforms.ts
src/helpers/createDtsExports.ts
src/index.ts
src/options.ts

feat: enable compatibility with `noUncheckedIndexedAccess`

---

src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getCssExports.ts
src/helpers/getDtsSnapshot.ts
src/index.ts

fixes an issue with `scss` and `less` files not respecting the project's root directory when importing other files by passing the ts root directory information to the renderer.
Should fix #146
* `less` fix is tested on my local machine.
* `scss` fix is untested. 
* This commit does not add any new test for this feature, but old tests are fixed

fix: pass through project root to Sass and Less

---

src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/createDtsExports.ts
src/options.ts

feat: optionally allow any additional classes

---

src/helpers/getCssExports.ts

This adds support for sourcemaps for less as well.

support goToDefinition also for less

---

src/importers/__tests__/sassTildeImporter.ts
src/importers/sassTildeImporter.ts

This change fixes a bug when importing partial sass files from `node_modules` which happen to have their basename exist also in some part of the dirname. 
For example, `@import '~sass-mq/mq';` should resolve to `node_modules/sass-mq/_mq.scss` but instead is looking for `node_modules/sass-_mq/mq.scss`.

fix sass tilde importer partials support

---

README.md
src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getCssExports.ts
src/options.ts

feat: add `additonalData` feature

---

src/helpers/createDtsExports.ts

This resolves a bug where lines could fail to be matched, resulting in negative line matches.
The previous code failed to check that `indexOf` values were above zero.

fix: improve CSS classname regexp

---

src/helpers/__tests__/__snapshots__/getDtsSnapshot.test.ts.snap
src/helpers/createDtsExports.ts

This functionality was accidentally removed when `goToDefinition` was in testing, and has now been restored.
Note that `classes` was renamed to `_classes` to mitigate the risk of a clashing variable name.

fix: restore named exports for `goToDefinition`

---

src/helpers/__tests__/getDtsSnapshot.test.ts
src/helpers/getCssExports.ts
src/helpers/getDtsSnapshot.ts
src/helpers/logger.ts
src/index.ts
src/options.ts

I mentioned this on https://github.com/mrmckeb/typescript-plugin-css-modules/pull/211#discussion_r1133048494, but, it was straightforward to send a PR for.
This PR:
- Makes imports consistent, named `tsModule` and `type` imported.
- Doesn't use any values from an imported typescript, as the one provided by `init` is the right one to be using.

Fix use of non-init provided typescript lib, use consistent imports

---

src/helpers/getDtsSnapshot.ts
src/index.ts

This prevents the VSCode plugin from crashing when an imported css/scss/etc... file does not exist.
A more elegant solution would be to check if the file exists before the `readFileSync` call.
Will also fix: https://github.com/mrmckeb/typescript-plugin-css-modules/issues/216

fix: check if file exists before processing

---

src/index.ts

Fixes #227.
This change generalizes "module resolution with failed lookup locations" so that it works for newer implementations of the typescript language server,  which provide such information in the response for `resolveModuleNameLiterals`, rather than implementing a separate `getResolvedModuleWithFailedLookupLocationsFromCache`.
Tested locally in a project using Typescript 5 and path aliases, and imports like:
```ts
import {
editorContainer,
tableOfContentsContainer,
} from "@/components/app.module.css"
```
which were failing before this change now successfully show type information and support "Go to Definition", etc.

fix: update module resolution for non-relative paths

---

README.md
src/helpers/cssExtensions.ts

docs: update README regexp
